const conversationalTemplates = {
    greetingMessages: ['hola no te voy a mentir, soy solo un robot automatizado, pero muy sensual y binario', 'hola soy un robot programado para hablarte, pero soy sensual, algoritimicamente caliente y latino, bueno latino no', 'soy un robot que viene del futro en una mision secreata', 'soy un robot que viene del fturo en una mision secreta'],
    randomQuestions:[' yo estoy bien gracias por no preguntar. Quiero saber cosas importantes de vos, te gusta el pan lactal integral', 'bien, queria preguntarte si tenes la antitetanica', 'te enteraste que los ornitorrincos (no se como se escibe) brillan en la oscuridad','viste que la cerveza corona no tiene gluten', 'Pensas que napelon era bajito,o que la gente de la epoca era muy alta?'],
    genericResponds: ['Estoy de acuerdo con todo eso, pero quiero saber mas detalles', 'Gran respuesta!!! algo que agregar?','Gran respuesta!!!, tenes mucha sabiduria',,'Mejor pajaro en mano, siempre digo, pensas que no entdes? o sera que mi screep derobot es una garcha'],
    interestingFacts: ['Sabias que hay un avispon en estados unidos que esta matando gente?'],
    closeSell: ['Bueno quiero confesarte que realmente soy un robot seductor mi creador se llama Diego y es el de las fotos, lo queres conocer?'],
    doubleCloseSell: ['te puedo pasar su instagram, pero es exactamente su plan maquiavelico'],
    cool: ['diegoerrero sin la h es su instagram, hace videos tan estupidos como la idea de programar su propio robot para promocionarlos','diegoerrero sin la h es su instagram', 'diegoerrero sin la h es su instagram, te advierto que sus videos generaran daños mentales: o sea que clase de persona crea un robot seductor para que la gente vaya a su ig?'],
    startInteristingFacts: ['recorda que soy un robot y no entieno lo que decis, pero en mi ultima actualizacion estoy  programado para darte datos interesantes que no se realmente si son verdad'],
    fact1: [ `McDonald's una vez hizo brócoli con sabor a chicle, el intento de hacer que los niños comieran más saludablemente no fue bien recibido por los evaluadores de niños, que estaban "confundidos por el sabor". te gusto? te puedo seguir contando a pesar de que no quieras si queres?`],
    fact2: ['Algunos hongos crean zombis y luego controlan sus mentes El hongo tropical Ophiocordyceps infecta el sistema nervioso central de las hormigas. Para cuando los hongos han estado en los cuerpos de los insectos durante nueve días, tienen un control completo sobre los movimientos del huésped. Obligan a las hormigas a trepar a los árboles, luego convulsionan y caen en el suelo fresco y húmedo de abajo, donde prosperan los hongos. Una vez allí, el hongo espera hasta el mediodía solar exacto para obligar a la hormiga a morder una hoja y matarla. Te gustaria ser una hormiga zombie? queres que te siga contando sin tu consentimiento o con?'],
    disclaimer: ['Toma en cuenta que soy un robot, y no entiendo lo que decis solo hablo ignorando a mi comenzal, como un adulto mayor'],
    fact3:[` che sabias que las primeras naranjas no eran naranjas.  Las naranjas originales del sudeste asiático eran un híbrido mandarina-pomelo, y en realidad eran verdes. De hecho, las naranjas en regiones más cálidas como Vietnam y Tailandia aún permanecen verdes hasta la madurez. `],
    fact4:[` sabes que hay un híbrido de vaca y bisonte se llama "beefalo"Incluso lo podes comprar su carne en al menos 21 estados de eeuu. `],
    disclaimer2: ['A esta altura quizas todavia sigas dudando si soy un robot o no, parece poco creible que diego se halla ocupado de programar un robot para hacer esto, pero si relees la conversacion vas a ver que realmente nunca conteste a anda de lo que dijiste. Porque simplemente no lo entiendo. Quizas en la proxima actualizacion mejore. Si me seguis hablando sigo con los datos pocos interesantes'],
    fact5: [`Escocia tiene 421 palabras para "nieve" Algunos ejemplos: sneesl (empezar a llover o nevar); feefle (girar); flinkdrinkin (una nieve ligera). Una verga esta no?`],
    fact6: [`Con esta me senti identificado, Samsung prueba la durabilidad del teléfono con un robot con forma de culo humano,  La gente guarda sus teléfonos en los bolsillos de atras todo el tiempo. Ahora me preguntaras si yo tengo forma de culo, o porque  me preste a semejante chiste facil.`],
    fact7:[ `Los manies no son técnicamente nueces Son legumbres. Según Merriam-Webster, una nuez es solo una nuez si es "una fruta seca de cáscara dura o una semilla con una cáscara o cáscara separables y un grano interior". Eso significa que las nueces, las almendras, los anacardos y los pistachos tampoco son nueces. Son semillas. con esta te mate!! Seguimos? si qures seguir escribe que no, o que si. Yo sigo` ],
    fact8:[`Los bomberos utilizan agentes humectantes para humedecer el agua Los productos químicos reducen la tensión superficial del agua corriente para que sea más fácil de esparcir y empapar en los objetos, razón por la cual se la conoce como "agua húmeda".`],
    fact9: [`Sabias que diego se canso de copiar y pegar datos para que  yo los diga, asi que con esta me despido. Muchas gracias por utilizarme. La pasaste bien? mucho mejor que hablar con diego te lo aseguro! no voy a seguir respondiendo porque se me acabo el screep. Saludos!!`]
    //  interestingFacts2: ['Del 1 al 10 como calificarias la experiencia de hablar con migo. Pensas que fue mas divertido que hablar con un ser humano?' ],

}

export default conversationalTemplates